### ISSUE TITLE
Is the gate same at each layer?

### ISSUE THREAD

**Issue by zhuango** [qiufengyuyi/bert-of-theseus-tf#2]
Hi, thanks for the TF implementations for paper [BERT-of-Theseus](http://arxiv.org/abs/2002.02925). I am reproducing the results of BERT-of-Theseus and I have a question about the [gate](https://github.com/qiufengyuyi/bert-of-theseus-tf/blob/d5b3ec7c061d2da4c283de0bec7f1bc4e9a35172/bert/modeling_theseus.py#L898) implementations. From the logic [here](https://github.com/qiufengyuyi/bert-of-theseus-tf/blob/d5b3ec7c061d2da4c283de0bec7f1bc4e9a35172/bert/modeling_theseus.py#L968), it seems that the gates are the same at each successor layer for one minibatch, which means layers of the model are ALL from either original BERT or the successor. But the proposed BERT-of-Theseus states that just some of the original layers (not all, initially) are replaced with successor layers. Is it a bug or my misunderstanding? Thank you!

**Comment by qiufengyuyi** [comment]
yes,the best implementation is dynamically applying different gate prob for different data. but for the bad mechanism of tf.estimator ,it is really hard to do so. If you are using tf 2.0 or pytorch ,you can implement it as your method

**Comment by qiufengyuyi** [comment]
> Hi, thanks for the TF implementations for paper [BERT-of-Theseus](http://arxiv.org/abs/2002.02925). I am reproducing the results of BERT-of-Theseus and I have a question about the [gate](https://github.com/qiufengyuyi/bert-of-theseus-tf/blob/d5b3ec7c061d2da4c283de0bec7f1bc4e9a35172/bert/modeling_theseus.py#L898) implementations. From the logic [here](https://github.com/qiufengyuyi/bert-of-theseus-tf/blob/d5b3ec7c061d2da4c283de0bec7f1bc4e9a35172/bert/modeling_theseus.py#L968), it seems that the gates are the same at each successor layer for one minibatch, which means layers of the model are ALL from either original BERT or the successor. But the proposed BERT-of-Theseus states that just some of the original layers (not all, initially) are replaced with successor layers. Is it a bug or my misunderstanding? Thank you!

yes,the best implementation is dynamically applying different gate prob for different data. but for the bad mechanism of tf.estimator ,it is really hard to do so. If you are using tf 2.0 or pytorch ,you can implement it as your method

**Comment by qiufengyuyi** [comment]
> Hi, thanks for the TF implementations for paper [BERT-of-Theseus](http://arxiv.org/abs/2002.02925). I am reproducing the results of BERT-of-Theseus and I have a question about the [gate](https://github.com/qiufengyuyi/bert-of-theseus-tf/blob/d5b3ec7c061d2da4c283de0bec7f1bc4e9a35172/bert/modeling_theseus.py#L898) implementations. From the logic [here](https://github.com/qiufengyuyi/bert-of-theseus-tf/blob/d5b3ec7c061d2da4c283de0bec7f1bc4e9a35172/bert/modeling_theseus.py#L968), it seems that the gates are the same at each successor layer for one minibatch, which means layers of the model are ALL from either original BERT or the successor. But the proposed BERT-of-Theseus states that just some of the original layers (not all, initially) are replaced with successor layers. Is it a bug or my misunderstanding? Thank you!

sorry , i have misunderstood your question. my bad!!!
you're right ,i have upload the wrong code for using same gate for all layers. i have modified the code and commit on the master branch. @zhuango

**Comment by zhuango** [comment]
Thanks for addressing my question. Closing this issue.
